DROP TABLE IF EXISTS file_uploads;

CREATE TABLE file_uploads (
id SERIAL PRIMARY KEY,
filename VARCHAR(255) NOT NULL,
file_size INT NOT NULL,
upload_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
